blank_issues_enabled: false
contact_links:
  - name: "💡 Suggest a feature ☛ please open a discussion instead of an issue"
    url: https://github.com/tarsius/.github/wiki/Feature-Requests
    about: Start a discussion suggesting an improvement or a new feature.
  - name: "🆘 Request help ☛ please open a discussion instead of an issue"
    url: https://github.com/tarsius/.github/wiki/Support
    about: Please search, ask and answer questions here.
